# Generated by Django 4.2.4 on 2023-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tasks_assigned',
        ),
        migrations.AddField(
            model_name='employee',
            name='tasks_assigned',
            field=models.TextField(blank=True),
        ),
    ]
