# Generated by Django 4.2.4 on 2023-08-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_employee_tasks_assigned_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeTask',
        ),
        migrations.AddField(
            model_name='cofounders',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cofounders/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
