# Generated by Django 4.2.4 on 2023-11-05 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_chefuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('veg_non_veg', models.CharField(default=None, max_length=7)),
                ('popularity_state', models.CharField(blank=True, max_length=100)),
                ('cuisine', models.CharField(blank=True, default=None, max_length=100)),
                ('course_type', models.CharField(default=None, max_length=12)),
                ('cooking_time', models.CharField(blank=True, default=None, max_length=10)),
                ('dish_picture', models.ImageField(blank=True, null=True, upload_to='dish_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_set', to='users.chefuser')),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=200)),
                ('instruction_video_url', models.CharField(blank=True, max_length=500)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='api.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.dish')),
            ],
        ),
    ]
