# Generated by Django 4.2.4 on 2023-08-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooking_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='customizable_ingredients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='main_course_starter_dessert',
            field=models.CharField(choices=[('MainCourse', 'Main Course'), ('Starter', 'Starter'), ('Dessert', 'Dessert')], default='MainCourse', max_length=12),
        ),
        migrations.AddField(
            model_name='dish',
            name='popularity_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='quantity',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='veg_non_veg',
            field=models.CharField(choices=[('Veg', 'Vegetarian'), ('NonVeg', 'Non-Vegetarian')], default='Veg', max_length=7),
        ),
        migrations.AlterField(
            model_name='dish',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_set', to='api.chef'),
        ),
    ]
