# Generated by Django 4.2.4 on 2023-10-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_chefuser"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instruction_text", models.TextField()),
                ("time_required", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Instructions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="dish",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="instructions",
        ),
        migrations.AddField(
            model_name="dish",
            name="cooking_time",
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name="dish",
            name="cuisine",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dish",
            name="customizable_ingredients",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dish",
            name="dish_picture",
            field=models.ImageField(blank=True, null=True, upload_to="dish_images/"),
        ),
        migrations.AddField(
            model_name="dish",
            name="dish_video_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="dish",
            name="main_course_starter_dessert",
            field=models.CharField(
                choices=[
                    ("MainCourse", "Main Course"),
                    ("Starter", "Starter"),
                    ("Dessert", "Dessert"),
                ],
                default="MainCourse",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="popularity_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dish",
            name="veg_non_veg",
            field=models.CharField(
                choices=[("Veg", "Vegetarian"), ("NonVeg", "Non-Vegetarian")],
                default="Veg",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="chef",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_set",
                to="users.chefuser",
            ),
        ),
        migrations.DeleteModel(
            name="Chef",
        ),
        migrations.AddField(
            model_name="instructions",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructions",
                to="api.dish",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="api.dish",
            ),
        ),
    ]
