# Generated by Django 4.2.4 on 2023-11-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_dish_customizable_ingredients"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DishInstruction",
        ),
    ]
