# Generated by Django 4.2.4 on 2023-08-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chefuser'),
        ('api', '0002_dish_cooking_time_dish_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_set', to='users.chefuser'),
        ),
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
