# Generated by Django 4.2.4 on 2023-11-05 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_dishinstruction"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dish",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="course_type",
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name="dish",
            name="cuisine",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="dish",
            name="veg_non_veg",
            field=models.CharField(default=None, max_length=7),
        ),
    ]
