# Generated by Django 4.2.4 on 2023-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dish_chef_delete_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_picture',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
    ]
