# Generated by Django 4.2.4 on 2023-11-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_dish_dish_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cooking_time',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
