# Generated by Django 4.2.4 on 2023-11-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_kitchen_equiments_dish_kitchen_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
