# Generated by Django 4.2.4 on 2023-11-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_dish_created_at_dish_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="course_type",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name="dish",
            name="veg_non_veg",
            field=models.CharField(default=None, max_length=16),
        ),
    ]
