# Generated by Django 4.2.4 on 2023-11-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_dish_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
