# Generated by Django 4.2.4 on 2023-09-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_dishinstruction_remove_dish_instructions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="instructions",
        ),
        migrations.AddField(
            model_name="dish",
            name="instructions",
            field=models.TextField(default=None),
        ),
    ]
