# Generated by Django 4.2.4 on 2023-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_dish_instructions_dish_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="instructions",
            field=models.TextField(default=False),
        ),
    ]
