# Generated by Django 4.2.4 on 2023-09-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_dish_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="number_of_people",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
