# Generated by Django 4.2.4 on 2023-11-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_dish_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
