# Generated by Django 4.2.4 on 2023-11-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_dish_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="kitchen_equipments",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
