# Generated by Django 4.2.4 on 2023-11-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_dish_kitchen_equipments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructions",
            name="time",
            field=models.CharField(max_length=50),
        ),
    ]
