# Generated by Django 4.2.4 on 2023-10-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_dish_ingredients_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="number_of_people",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="quantity",
        ),
        migrations.AddField(
            model_name="dish",
            name="dish_video_url",
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name="dish",
            name="cooking_time",
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name="Instructions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=200)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="api.dish",
                    ),
                ),
            ],
        ),
    ]
