# Generated by Django 4.2.4 on 2023-10-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_dish_instructions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="dish_video_url",
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
